### ISSUE TITLE
Add Simple Analytics event tracking

### ISSUE THREAD

**Issue by khrome83** [khrome83/khrome.dev#13]
- [x] Should record an event when a share button is clicked
- [x] Should record an event when the newsletter is signed up for
- [x] Should record an event when contact form is used

**Comment by khrome83** [comment]
Simple Analytics currently uses cookies for events, and it requires additional JavaScript. Going to wait on this until the SA solution improves.

**Comment by khrome83** [comment]
This has now been fixed.
