### ISSUE TITLE
Add Milestones to Indie Hackers

### ISSUE THREAD

**Issue by khrome83** [khrome83/khrome.dev#18]
- [ ] Reached 750 Pageviews in a Month
- [ ] Had carwow.co.uk reach out about 404 page article
- [ ] First entry within a newsletter
- [ ] Added Social Share Widgets
- [ ] Setup Revue Newsletter

**Comment by khrome83** [comment]
![IMG_3685](https://user-images.githubusercontent.com/1844739/70623537-f8910080-1be3-11ea-83bf-341c62427ab3.PNG)

**Comment by khrome83** [comment]
![IMG_3671](https://user-images.githubusercontent.com/1844739/70623616-21b19100-1be4-11ea-9c2f-d6bc33e48eef.PNG)

**Comment by khrome83** [comment]
![IMG_821D887D2CA9-1](https://user-images.githubusercontent.com/1844739/70708992-76671180-1ca1-11ea-878f-b2cee4a27140.jpeg)
